//! `horizon-core` — the shared schema home for the Horizon concept.
//!
//! It declares `Magnitude`, the cross-crate trust noun the Horizon
//! schema imports. The emitted module lives at `src/schema/magnitude.rs`
//! and is regenerated by `build.rs` from `schema/magnitude.schema`.

pub mod schema {
    pub mod magnitude {
        include!("schema/magnitude.rs");
    }
}
