//! `horizon-next` — Horizon as a schema-driven component (concept).
//!
//! Every datatype in [`schema`] is generated by `build.rs` from
//! `schema/horizon.schema` through the schema-next + schema-rust-next
//! pipeline. The schema declares Horizon as a component with an
//! `Input` (`Project ClusterProposal`) and an `Output`
//! (`Projected <map>` / `Rejected ProjectionError`), imports
//! `Magnitude` from the `horizon-core` crate across the crate
//! boundary, and uses collections (`BTreeMap`, `Vec`, `Option`) for
//! the cluster aggregate roots.
//!
//! This crate adds only BEHAVIOR — the projection method — on the
//! schema-emitted nouns. The data shapes are not hand-written here;
//! editing the shape means editing the schema and regenerating.

pub mod schema {
    pub mod horizon {
        include!("schema/horizon.rs");
    }
}

use std::collections::BTreeMap;

use schema::horizon::{
    ClusterProposal, NodeConfig, NodeName, NodeProposal, Output, ProjectionError, RejectionReason,
};

use horizon_core::schema::magnitude::Magnitude;

/// Projection lives as a method on the schema-emitted `ClusterProposal`
/// noun — mirroring the real `horizon-rs` `ClusterProposal::project`,
/// scaled to the concept slice. It turns the authored cluster proposal
/// into the per-node `Output`: each trusted node becomes a `NodeConfig`
/// keyed by its `NodeName`; a node whose trust is `Zero` is actively
/// distrusted and dropped from the projection (the real Horizon rule).
/// An empty cluster is rejected, because a Horizon with no nodes is not
/// a usable projection target.
impl ClusterProposal {
    pub fn project(&self) -> Output {
        if self.nodes.is_empty() {
            return Output::Rejected(ProjectionError(RejectionReason(String::from(
                "cluster has no nodes",
            ))));
        }
        let mut configs: BTreeMap<NodeName, NodeConfig> = BTreeMap::new();
        for (name, proposal) in &self.nodes {
            if proposal.trust == Magnitude::Zero {
                // trust=Zero marks a node as actively distrusted; drop
                // it from the projected horizon entirely.
                continue;
            }
            configs.insert(name.clone(), proposal.project_node(self));
        }
        if configs.is_empty() {
            return Output::Rejected(ProjectionError(RejectionReason(String::from(
                "every node was distrusted",
            ))));
        }
        Output::Projected(configs)
    }
}

/// The per-node projection step, again a method on the schema-emitted
/// `NodeProposal`. The node inherits the cluster's binary-cache URL (if
/// the cluster declared one) and merges the cluster-wide services with
/// its own.
impl NodeProposal {
    fn project_node(&self, cluster: &ClusterProposal) -> NodeConfig {
        let mut services = cluster.cluster_services.clone();
        services.extend(self.services.iter().cloned());
        NodeConfig {
            role: self.role.clone(),
            trust: self.trust.clone(),
            services,
            cache: cluster.cache.as_ref().map(|cache| cache.0.clone()),
        }
    }
}
