//! `horizon-next` — Horizon as a schema-driven component (concept).
//!
//! Every datatype in [`schema`] is generated by `build.rs` from
//! `schema/horizon.schema` through the schema-next + schema-rust-next
//! pipeline. The schema declares Horizon as a component with an
//! `Input` (`Project ClusterProposal`) and an `Output`
//! (`Projected <map>` / `Rejected ProjectionError`), imports
//! `Magnitude` from the `horizon-core` crate across the crate
//! boundary, and uses collections (`BTreeMap`, `Vec`, `Option`) for
//! the cluster aggregate roots.
//!
//! This crate adds only BEHAVIOR — the projection method — on the
//! schema-emitted nouns. The data shapes are not hand-written here;
//! editing the shape means editing the schema and regenerating.

pub mod schema {
    pub mod horizon {
        include!("schema/horizon.rs");
    }
}

use std::collections::BTreeMap;

use schema::horizon::{
    ClusterProposal, Input, NexusEngine, NodeConfig, NodeName, NodeProposal, Output, Plane,
    ProjectionError, RejectionReason, SemaEngine, SignalEngine,
};

use horizon_core::schema::magnitude::Magnitude;

/// Projection lives as a method on the schema-emitted `ClusterProposal`
/// noun — mirroring the real `horizon-rs` `ClusterProposal::project`,
/// scaled to the concept slice. It turns the authored cluster proposal
/// into the per-node `Output`: each trusted node becomes a `NodeConfig`
/// keyed by its `NodeName`; a node whose trust is `Zero` is actively
/// distrusted and dropped from the projection (the real Horizon rule).
/// An empty cluster is rejected, because a Horizon with no nodes is not
/// a usable projection target.
impl ClusterProposal {
    pub fn project(&self) -> Output {
        if self.nodes.is_empty() {
            return Output::Rejected(ProjectionError(RejectionReason(String::from(
                "cluster has no nodes",
            ))));
        }
        let mut configs: BTreeMap<NodeName, NodeConfig> = BTreeMap::new();
        for (name, proposal) in &self.nodes {
            if proposal.trust == Magnitude::Zero {
                // trust=Zero marks a node as actively distrusted; drop
                // it from the projected horizon entirely.
                continue;
            }
            configs.insert(name.clone(), proposal.project_node(self));
        }
        if configs.is_empty() {
            return Output::Rejected(ProjectionError(RejectionReason(String::from(
                "every node was distrusted",
            ))));
        }
        Output::Projected(configs)
    }
}

/// The per-node projection step, again a method on the schema-emitted
/// `NodeProposal`. The node inherits the cluster's binary-cache URL (if
/// the cluster declared one) and merges the cluster-wide services with
/// its own.
impl NodeProposal {
    fn project_node(&self, cluster: &ClusterProposal) -> NodeConfig {
        let mut services = cluster.cluster_services.clone();
        services.extend(self.services.iter().cloned());
        NodeConfig {
            role: self.role.clone(),
            trust: self.trust.clone(),
            services,
            cache: cluster.cache.as_ref().map(|cache| cache.0.clone()),
        }
    }
}

// The running three-engine chain (records 1028/1030/1054). The three
// trait-ordered engines below implement the schema-emitted
// `SignalEngine` / `NexusEngine` / `SemaEngine`, each matching directly
// on the data-carrying `Plane` enum (record 1054 — no separate kind tag
// beside an envelope, record 1052) and threading the origin route minted
// at ingress (records 1038/1039) through every hop. `Plane::drive` (the
// schema-emitted chain) wires them: Signal validates and pushes to
// Nexus, Nexus executes the projection and pushes to Sema, Sema applies
// the reply to durable state and returns the reply Plane echoing the
// origin route. This is a real chain that drives, not emitted-but-dead
// scaffolding.

/// Signal-plane engine error: the ingress request was structurally
/// inadmissible before any projection ran.
#[derive(Debug, PartialEq, Eq)]
pub enum SignalRejection {
    NotAnIngressSignal,
}

/// Nexus-plane engine error: the chain reached Nexus on the wrong plane.
#[derive(Debug, PartialEq, Eq)]
pub enum NexusFault {
    NotAdmittedToNexus,
}

/// Sema-plane engine error: the chain reached Sema on the wrong plane.
#[derive(Debug, PartialEq, Eq)]
pub enum SemaFault {
    NotHandedToSema,
}

/// The Signal engine. It owns no durable state — it is the admission
/// gate — but it carries its configured ingress policy as data so the
/// behavior lives on a non-zero-sized type rather than a free function.
pub struct SignalGate {
    reject_empty_cluster: bool,
}

impl SignalGate {
    pub fn new() -> Self {
        Self {
            reject_empty_cluster: true,
        }
    }
}

impl Default for SignalGate {
    fn default() -> Self {
        Self::new()
    }
}

impl SignalEngine for SignalGate {
    type Error = SignalRejection;

    /// Validate the ingress `Plane::Signal(route, Input::Project(..))`
    /// and admit it onto the Nexus plane, carrying the same origin route.
    fn admit(&self, signal: Plane) -> Result<Plane, Self::Error> {
        match signal {
            Plane::Signal(route, Input::Project(proposal)) => {
                if self.reject_empty_cluster && proposal.nodes.is_empty() {
                    return Err(SignalRejection::NotAnIngressSignal);
                }
                Ok(Plane::Nexus(route, Input::Project(proposal)))
            }
            _ => Err(SignalRejection::NotAnIngressSignal),
        }
    }
}

/// The Nexus engine. It executes the admitted request — running the
/// projection that is itself a method on the schema-emitted
/// `ClusterProposal` — and hands the reply onto the Sema plane.
pub struct ProjectionNexus;

impl ProjectionNexus {
    pub fn new() -> Self {
        Self
    }
}

impl Default for ProjectionNexus {
    fn default() -> Self {
        Self::new()
    }
}

impl NexusEngine for ProjectionNexus {
    type Error = NexusFault;

    fn execute(&self, nexus: Plane) -> Result<Plane, Self::Error> {
        match nexus {
            Plane::Nexus(route, Input::Project(proposal)) => {
                let output = proposal.project();
                Ok(Plane::Sema(route, output))
            }
            _ => Err(NexusFault::NotAdmittedToNexus),
        }
    }
}

/// The Sema engine. It owns the durable projection state — the map of
/// the last projected node configurations per origin route — applies the
/// reply to that state, and returns the reply Plane to be echoed back to
/// the caller. The state map is the data the engine's behavior reads and
/// writes, so the engine is a real data-bearing noun.
pub struct ProjectionSema {
    last_projection: BTreeMap<NodeName, NodeConfig>,
    applied_count: usize,
}

impl ProjectionSema {
    pub fn new() -> Self {
        Self {
            last_projection: BTreeMap::new(),
            applied_count: 0,
        }
    }

    pub fn last_projection(&self) -> &BTreeMap<NodeName, NodeConfig> {
        &self.last_projection
    }

    pub fn applied_count(&self) -> usize {
        self.applied_count
    }
}

impl Default for ProjectionSema {
    fn default() -> Self {
        Self::new()
    }
}

impl SemaEngine for ProjectionSema {
    type Error = SemaFault;

    fn apply(&mut self, sema: Plane) -> Result<Plane, Self::Error> {
        match sema {
            Plane::Sema(route, output) => {
                if let Output::Projected(configs) = &output {
                    self.last_projection = configs.clone();
                    self.applied_count += 1;
                }
                Ok(Plane::Sema(route, output))
            }
            _ => Err(SemaFault::NotHandedToSema),
        }
    }
}
