// @generated by schema-rust-next

pub type Text = String;
pub type Integer = u64;

#[derive(Clone, Debug, PartialEq, Eq)]
pub enum NotaDecodeError {
    Parse(String),
    ExpectedSingleRoot { found: usize },
    ExpectedDelimited { type_name: &'static str, delimiter: &'static str },
    ExpectedRootCount { type_name: &'static str, expected: usize, found: usize },
    ExpectedAtom { type_name: &'static str },
    UnknownVariant { enum_name: &'static str, variant: String },
    InvalidInteger { value: String },
}

impl std::fmt::Display for NotaDecodeError {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Parse(error) => write!(formatter, "{error}"),
            Self::ExpectedSingleRoot { found } => write!(formatter, "expected exactly one NOTA root object, found {found}"),
            Self::ExpectedDelimited { type_name, delimiter } => write!(formatter, "expected {type_name} to be a {delimiter} block"),
            Self::ExpectedRootCount { type_name, expected, found } => write!(formatter, "expected {type_name} to hold {expected} root objects, found {found}"),
            Self::ExpectedAtom { type_name } => write!(formatter, "expected {type_name} atom"),
            Self::UnknownVariant { enum_name, variant } => write!(formatter, "unknown {enum_name} variant {variant}"),
            Self::InvalidInteger { value } => write!(formatter, "invalid integer {value}"),
        }
    }
}

impl std::error::Error for NotaDecodeError {}

pub struct NotaSource<'a> {
    source: &'a str,
}

impl<'a> NotaSource<'a> {
    pub fn new(source: &'a str) -> Self {
        Self { source }
    }

    pub fn parse_root(&self) -> Result<nota_next::Block, NotaDecodeError> {
        let document = nota_next::Document::parse(self.source).map_err(|error| NotaDecodeError::Parse(error.to_string()))?;
        if document.holds_root_objects() != 1 {
            return Err(NotaDecodeError::ExpectedSingleRoot { found: document.holds_root_objects() });
        }
        Ok(document.root_object_at(0).expect("root count checked").clone())
    }
}

pub struct NotaBlock<'a> {
    block: &'a nota_next::Block,
}

impl<'a> NotaBlock<'a> {
    pub fn new(block: &'a nota_next::Block) -> Self {
        Self { block }
    }

    pub fn expect_children(
        &self,
        delimiter: nota_next::Delimiter,
        delimiter_name: &'static str,
        type_name: &'static str,
        expected: usize,
    ) -> Result<&'a [nota_next::Block], NotaDecodeError> {
        match self.block {
            nota_next::Block::Delimited { delimiter: found, root_objects, .. } if *found == delimiter => {
                if root_objects.len() != expected {
                    return Err(NotaDecodeError::ExpectedRootCount { type_name, expected, found: root_objects.len() });
                }
                Ok(root_objects)
            }
            _ => Err(NotaDecodeError::ExpectedDelimited { type_name, delimiter: delimiter_name }),
        }
    }

    pub fn parse_text(&self) -> Result<Text, NotaDecodeError> {
        if let Some(text) = self.block.demote_to_string() {
            return Ok(text.to_owned());
        }
        match self.block {
            nota_next::Block::Delimited { delimiter: nota_next::Delimiter::SquareBracket, root_objects, .. } => {
                root_objects.iter().map(|block| NotaBlock::new(block).parse_text()).collect::<Result<Vec<_>, _>>().map(|parts| parts.join(" "))
            }
            _ => Err(NotaDecodeError::ExpectedDelimited { type_name: "Text", delimiter: "text atom or square bracket" }),
        }
    }

    pub fn parse_integer(&self) -> Result<Integer, NotaDecodeError> {
        let value = self.block.demote_to_string().ok_or(NotaDecodeError::ExpectedAtom { type_name: "Integer" })?;
        value.parse::<Integer>().map_err(|_| NotaDecodeError::InvalidInteger { value: value.to_owned() })
    }
}

pub struct NotaText<'a> {
    value: &'a str,
}

impl<'a> NotaText<'a> {
    pub fn new(value: &'a str) -> Self {
        Self { value }
    }

    pub fn format(&self) -> String {
        if self.value.contains("|]") {
            format!("[{}]", self.value.replace(']', " ]"))
        } else if self.value.chars().any(|character| matches!(character, '[' | ']' | '(' | ')' | '{' | '}' | ';' | '\n')) {
            format!("[|{}|]", self.value)
        } else {
            format!("[{}]", self.value)
        }
    }
}

#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Magnitude {
    Zero,
    Min,
    Low,
    Medium,
    High,
    Max,
}

impl Magnitude {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        if let Some(variant) = block.demote_to_string() {
            return match variant {
                "Zero" => Ok(Self::Zero),
                "Min" => Ok(Self::Min),
                "Low" => Ok(Self::Low),
                "Medium" => Ok(Self::Medium),
                "High" => Ok(Self::High),
                "Max" => Ok(Self::Max),
                other => Err(NotaDecodeError::UnknownVariant { enum_name: "Magnitude", variant: other.to_owned() }),
            };
        }
        Err(NotaDecodeError::ExpectedAtom { type_name: "Magnitude" })
    }

    pub fn to_nota(&self) -> String {
        match self {
            Self::Zero => "Zero".to_owned(),
            Self::Min => "Min".to_owned(),
            Self::Low => "Low".to_owned(),
            Self::Medium => "Medium".to_owned(),
            Self::High => "High".to_owned(),
            Self::Max => "Max".to_owned(),
        }
    }
}

